modLoader="javafml"
loaderVersion="[44,)"
license="GNU General Public License 3.0"

[[mods]]
modId="filtermod"
version="0.0.0"
displayName="Filter"
logoFile="filter.png"
credits="MrCrayfish on GitHub for the reference code"
authors="Lotkey"
description="Adds a new hopper variant that can filter items"

[[dependencies.filtermod]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.filtermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"

[modproperties.filtermod]
    catalogueItemIcon="filtermod:filter"
    configuredBackground="minecraft:textures/block/copper_ore.png"
